# fly.toml app configuration file generated for winnin on 2024-09-11T01:28:54-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'winnin'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
